version: '3'

services:
  ktap-ui-web:
    container_name: ktap-ui-web
    image: ktap-ui-web:latest
    build: ./ktap-ui-web
    ports:
      - 3000:80
    depends_on:
      - ktap-server
    networks:
      - ktap

  ktap-server:
    container_name: ktap-server
    image: ktap-server:latest
    build: ./ktap-server
    networks:
      - ktap

networks:
  ktap:
    driver: bridge
