version: '3'

services:
  ktap-ui-web:
    container_name: ktap-ui-web
    image: ktap-ui-web:latest
    build: ./ktap-ui-web
    ports:
      - 5173:80
    depends_on:
      - ktap-server
    networks:
      - ktap

  ktap-server:
    container_name: ktap-server
    image: ktap-server:latest
    build: ./ktap-server
    volumes:
      - ./runtime/public:/app/public:rw
      - ./runtime/prisma:/app/prisma:rw
    networks:
      - ktap

networks:
  ktap:
    driver: bridge
